apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
  - name: web-server
    image: nginx:1.21
    ports:
    - containerPort: 80
  - name: log-agent
    image: busybox:1.35
    command: ['sh', '-c']
    args: ['while true; do echo "$(date): Monitoring web-server"; sleep 30; done']
