apiVersion: v1
kind: Pod
metadata:
  name: resource-limited-pod
  labels:
    app: resource-demo
spec:
  containers:
  - name: nginx
    image: nginx:1.21
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"
    env:
    - name: APP_ENV
      value: "development"
