# kind-cluster-config.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: k8s-learning
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30080
        hostPort: 8080
        protocol: TCP
#This config ensures you can expose a Kubernetes Service on port 30080 and access it via 
#localhost:8080 from your host machine — great for future challenges involving web apps or APIs.
