apiVersion: apps/v1
kind: Deployment
metadata:
  name: strategic-deployment
  labels:
    app: strategic-app
spec:
  replicas: 6
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  selector:
    matchLabels:
      app: strategic-app
  template:
    metadata:
      labels:
        app: strategic-app
    spec:
      containers:
      - name: app
        image: nginx:1.21
        ports:
        - containerPort: 80
